name: r2-workflow
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cutadapt
  - seqkit
  - vsearch
  - biopython
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip
